name: miEPG

on:
  schedule:
    - cron: '00 00 * * *'
    - cron: '30 11 * * *'
    - cron: '30 18 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  create_canales:  # Trabajo para crear y subir canales.txt
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Python script (create canales.txt)
        run: python .github/workflows/generacanales.py

      - name: Commit and push canales.txt
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git add canales.txt
          git commit -m "Update canales.txt (automated)" --allow-empty
          git push
          
        shell: bash

  create_epg:  # Trabajo para crear y subir miEPG.xml
    runs-on: ubuntu-latest
    needs: create_canales  # Importante: Este trabajo depende del anterior
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Dar permisos de ejecución al script (Bash)  # Ya no necesitas Python aquí
        run: chmod +x .github/workflows/EPG_script.sh

      - name: Execute Bash script (create miEPG.xml)
        run: ./.github/workflows/EPG_script.sh
        shell: bash

      - name: Commit and push miEPG.xml
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull origin main
          git add miEPG.xml # Solo agrega el archivo .gz
          git commit -m "Update miEPG.xml(automated)" --allow-empty
          git push
                 
        shell: bash
